shopping/shopping/urls.py
from django.contrib import admin
from django.urls import path
from user.views import index, RegisterView, LoginView, logout
from product.views import (
    ProductList, ProductCreate, ProductDetail,
    ProductListAPI, ProductDetailAPI
)
from order.views import OrderCreate, OrderList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('logout/', logout),
    path('product/', ProductList.as_view()),
    path('product/<int:pk>', ProductDetail.as_view()),
    path('product/create/', ProductCreate.as_view()),
    path('order/', OrderList.as_view()),
    path('order/create/', OrderCreate.as_view()),

    path('api/product/', ProductListAPI.as_view()),
    path('api/product/<int:pk>', ProductDetailAPI.as_view()),
]

shopping/product/models.py
from django.db import models


# Create your models here.
class Product (models.Model):
    name = models.CharField(max_length=256, verbose_name='상품명')
    price = models.IntegerField(verbose_name='상품가격')
    description = models.TextField(verbose_name='상품설명')
    stock = models.IntegerField(verbose_name="재고")
    registered_dttm = models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'product'
        verbose_name = '상품'
        verbose_name_plural = '상품'

shopping/product/forms.py
from django import forms


class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={
            'required': '상품명을 입력해주세요.'
        },
        max_length=64, label='상품명'
    )
    price = forms.IntegerField(
        error_messages={
            'required': '상품가격을 입력해주세요.'
        },
        label='상품가격'
    )
    description = forms.CharField(
        error_messages={
            'required': '상품명을 입력해주세요.'
        },
        label='상품설명'
    )
    stock = forms.IntegerField(
        error_messages={
            'required': '재고를 입력해주세요.'
        },
        label='재고'
    )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        price = cleaned_data.get('price')
        description = cleaned_data.get('description')
        stock = cleaned_data.get('stock')

        if not (name and price and description and stock):
            self.add_error('name', '값이 없습니다.')
            self.add_error('price', '값이 없습니다.')

shopping/product/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from .models import Product
from .forms import RegisterForm
from order.forms import RegisterForm as OrderForm
from django.utils.decorators import method_decorator
from user.decorators import admin_required
from rest_framework import generics, mixins
from .serializers import ProductSerializer


# Create your views here.
class ProductListAPI(generics.GenericAPIView, mixins.ListModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class ProductDetailAPI(generics.GenericAPIView, mixins.RetrieveModelMixin):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)


class ProductList(ListView):
    model = Product
    template_name = 'product.html'
    context_object_name = 'product_list'


@method_decorator(admin_required, name='dispatch')
class ProductCreate(FormView):
    template_name = 'register_product.html'
    form_class = RegisterForm
    success_url = '/product/'

    def form_valid(self, form):
        product = Product(
            name=form.data.get('name'),
            price=form.data.get('price'),
            description=form.data.get('description'),
            stock=form.data.get('stock')
        )
        product.save()
        return super().form_valid(form)


class ProductDetail(DetailView):
    template_name = 'product_detail.html'
    queryset = Product.objects.all()
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderForm(self.request)
        return context

shopping/product/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    {% block header %}
    {% endblock %}
</head>
<body>
<div class="container">
    {% block contents %}
    {% endblock %}
</div>
</body>
</html>

shopping/product/templates/product.html
{% extends "base.html" %}
{% load humanize %}
{% block header %}
    <script>
        function product_detail(id){
            $.ajax({
                url: "/api/product/" + id,
                data: {},
                success: function(result){
                    $("#product-" + id).popover({
                        html: true,
                        content: result.name + "<br/>" + result.price
                    }).popover('show')
                },
            });
        }
        function product_leave(id){
            $("#product-" + id).popover('hide')
        }
        $(document).ready(function(){

        });
    </script>
{% endblock %}
{% block contents %}
<div class="row mt-5">
    <div class="col-12">
        <table class="table table-light">
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">상품명</th>
                    <th scope="col">가격</th>
                    <th scope="col">등록날짜</th>
                </tr>
            </thead>
            <tbody class="text-dark">
            {% for product in product_list %}
            <tr>
                <th scope="row">{{ product.id }}</th>
                <th scope="row"><a id="product-{{ product.id }}" onmouseenter="product_detail({{ product.id }})" onmouseleave="product_leave({{ product.id }})" href="/product/{{ product.id }}">{{ product.name }}</a></th>
                <th scope="row">{{ product.price|intcomma}} 원</th>
                <th scope="row">{{ product.registered_dttm|date:'Y-m-d H:i'}}</th>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

shopping/product/templates/product_detail.html
{% extends "base.html" %}
{% load humanize %}
{% block contents %}
    <div class="row mt-5">
        <div class="col-12">
            <div class="card" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <form method="post" action="/order/create/">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {% ifnotequal field.name 'product' %}
                                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                                    {% endifnotequal %}
                                    <input type="{{field.field.widget.input_type}}" class="form-control"
                                           id="{{field.id_for_label}}" name="{{field.name}}"  placeholder="{{field.label}}"
                                            value="{% ifequal field.name 'product' %}{{ product.id }}{% endifequal %}">
                                </div>
                                {% if field.errors %}
                                    <span style="color: red">{{ field.errors }}</span>
                                {% endif %}
                            {% endfor %}
                            <button type="submit" class="btn btn-primary">주문하기</button>
                        </form>
                    </li>
                    <li class="list-group-item">가격: {{ product.price|intcomma }} 원</li>
                    <li class="list-group-item">등록날짜: {{ product.registered_dttm|date:'Y-m-d H:i' }}</li>
                    <li class="list-group-item">재고: {{ product.stock|intcomma }} 개</li>
                    <li class="list-group-item">{{ product.description|safe }}</li>
                </ul>

            </div>
        </div>
    </div>
{% endblock %}

shopping/product/templates/register_product.html
{% extends "base.html" %}
{% block header %}
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_description').summernote({
                height:300
            });
        });
    </script>
{% endblock %}
{% block contents %}
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>상품 생성하기</h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            {{ error }}
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <form method="post" action=".">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {% ifequal field.name 'description' %}
                            <textarea class="form-control" id="{{field.id_for_label}}" name="{{field.name}}"></textarea>
                        {% else %}
                            <input type="{{field.field.widget.input_type}}" class="form-control" id="{{field.id_for_label}}" name="{{field.name}}"  placeholder="{{field.label}}">
                        {% endifequal %}
                    </div>
                    {% if field.errors %}
                        <span style="color: red">{{ field.errors }}</span>
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-primary">생성</button>
            </form>
        </div>
    </div>
{% endblock %}